<script lang="ts">
    import Input from "$components/Forms/Input.svelte";
	import { ndk } from "@kind0/ui-common";
	import { NDKArticle, type NostrEvent } from "@nostr-dev-kit/ndk";
    import { createEventDispatcher } from "svelte";
	import ContentEditor from './ContentEditor.svelte';
	import ArticleRenderShell from "$components/Event/Article/ArticleRenderShell.svelte";
	import ArticleCover from "$components/Editor/ArticleCover.svelte";
	import { openModal } from "$utils/modal";
	import CoverImageModal from "$modals/CoverImageModal.svelte";
	import TagInput from "$components/Editor/TagInput.svelte";
	import EventTags from "$components/Events/EventTags.svelte";
	import TagInputModal from "$modals/TagInputModal.svelte";
	import Tags from "$components/Events/Tags.svelte";
	import { Shuffle } from "phosphor-svelte";

    export let article: NDKArticle = new NDKArticle($ndk, {
        content: "",
    } as NostrEvent);

    const dispatch = createEventDispatcher();

    let contentAreaElement: HTMLElement;

    function onTitleKeyDown(e: KeyboardEvent) {
        if (e.key === "Enter") {
            e.preventDefault();
            // move focus to content
            if (contentAreaElement) contentAreaElement.focus();
        }
    }

    function fetchRandomImage() {
        const title = article.title || "Nature";
            fetch(`https://picsum.photos/800/600?random=${title}`)
                .then((res) => {
                    article.image = res.url;
                    article = article;
                    autoGeneratedImage = true;
                    showCoverImage = !!article.image;
                })
    }

    function titleChanged() {
        dispatch("titleChanged");

        if (autoGeneratedImage !== false) {
            console.log("fetching random image");
            fetchRandomImage();
        }
    }

    let autoGeneratedImage: boolean | undefined;

    let showCoverImage = !!article.image;
    let showSummary = !!article.summary;
    let showTags = article.getMatchingTags("t").length > 0;
    let tags: string[] = [];

    $: tags = Array.from(new Set(article.getMatchingTags("t").map(t => t[1])));

    function onSaveCover(article: NDKArticle) {
        autoGeneratedImage = false;
        article = article;
        showCoverImage = !!article.image;
        showTags = article.getMatchingTags("t").length > 0;
        tags = tags;
    }

    function onSaveTags(article: NDKArticle) {
        article = article;
        showCoverImage = !!article.image;
        showTags = article.getMatchingTags("t").length > 0;
        tags = tags;
    }

</script>

<ArticleRenderShell isFullVersion={true} isPreview={false}>
    <div slot="image" class="w-full">
        {#if showCoverImage && article.image}
            <button
                class="text-white text-sm font-normal w-full h-full"
                on:click={() => openModal(CoverImageModal, { article, onSave: onSaveCover })}
            >
                <div class="absolute left-2 top-2 z-50 flex flex-row gap-[1px] rounded-full overflow-hidden">
                    <button class="text-xs button-black bg-opacity-80 py-2 px-4">
                        Change cover image
                    </button>
    
                    {#if autoGeneratedImage}
                        <button class="text-xs button-black bg-opacity-80 py-2 px-4" on:click|preventDefault|stopPropagation={fetchRandomImage}>
                            <Shuffle class="w-4 h-4 inline" />
                        </button>
                    {/if}

                </div>
                
                <img src={article.image} alt="Cover image" class="w-full h-full object-cover" />
            </button>
        {:else}
            <button
                class="text-white text-sm font-normal w-full bg-base-300 h-full"
                on:click={() => openModal(CoverImageModal, { article, onSave: onSaveCover })}
            >
                <button class="button text-xs button-black relative z-50">
                    Add a cover image
                </button>
            </button>
        {/if}
    </div>

    <div slot="title">
        <Input
            bind:value={article.title}
            color="black"
            class="!bg-transparent !text-3xl border-none !p-0 rounded-lg focus:ring-0 !text-white font-['InterDisplay'] placeholder:text-white/50 placeholder:font-normal"
            placeholder="Add a title"
            on:keydown={onTitleKeyDown}
            on:change={titleChanged}
        />
    </div>

    <div slot="summary">
        {#if showSummary}
            <Input
                bind:value={article.summary}
                color="black"
                class="!bg-transparent text-lg border-none !p-0 rounded-lg focus:ring-0 font-['InterDisplay'] text-inherit placeholder:text-white/50 placeholder:font-normal"
                placeholder="Summary"
                autofocus={true}
            />
        {/if}
    </div>

    <div slot="tags">
        {#if !showSummary || !showTags}
            <div class="flex flex-row items-center gap-4 my-2">
                <button class:hidden={showSummary} class="add-metadata-button" on:click={() => showSummary = !showSummary}>Add summary</button>
                <button class:hidden={showTags} class="add-metadata-button" on:click={() => openModal(TagInputModal, { event: article, onSave: onSaveTags })}>Add #hashtags</button>
            </div>
        {/if}
        {#if showTags}
            <div class="flex flex-row gap-2">
                <Tags {tags} clickable={false} />
                <button on:click={() => openModal(TagInputModal, { event: article, onSave: onSaveTags })} class="add-metadata-button whitespace-nowrap">Edit #hashtags</button>
            </div>
        {/if}
    </div>

    <div slot="content" class="w-full">
        <ContentEditor
            bind:content={article.content}
            on:contentChanged
            on:submit
            on:focus
            on:blur
            class="font-serif text-lg min-h-[50vh]"
        />
    </div>
</ArticleRenderShell>

<style lang="postcss">
    .add-metadata-button {
        @apply text-white text-xs font-normal underline;
    }
</style>