<script lang="ts">
    import Input from '$components/ui/input/input.svelte';
	import { ndk } from "$stores/ndk.js";
	import { NDKArticle, type NostrEvent } from "@nostr-dev-kit/ndk";
    import { createEventDispatcher } from "svelte";
	import ContentEditor from './ContentEditor.svelte';
	import ArticleRenderShell from "$components/Event/Article/ArticleRenderShell.svelte";
	import { openModal } from "$utils/modal";
	import CoverImageModal from "$modals/CoverImageModal.svelte";
	import TagInputModal from "$modals/TagInputModal.svelte";
	import Tags from "$components/Events/Tags.svelte";
	import { Shuffle } from "phosphor-svelte";
	import { Button } from '$components/ui/button';
	import { appMobileView } from '$stores/app';
	import { slide } from 'svelte/transition';
    import * as Content from "$components/Content";
	import { NavigationOption } from '../../../app';
	import HorizontalOptionsList from '$components/HorizontalOptionsList.svelte';

    export let article: NDKArticle = new NDKArticle($ndk, {
        content: "",
    } as NostrEvent);

    const dispatch = createEventDispatcher();

    let contentAreaElement: HTMLElement;

    function onTitleKeyDown(e: KeyboardEvent) {
        if (e.key === "Enter") {
            e.preventDefault();
            // move focus to content
            if (contentAreaElement) contentAreaElement.focus();
        }
    }

    function fetchRandomImage() {
        const title = article.title || "Nature";
            fetch(`https://picsum.photos/800/600?random=${title}`)
                .then((res) => {
                    article.image = res.url;
                    article = article;
                    autoGeneratedImage = true;
                    showCoverImage = !!article.image;
                })
    }

    function titleChanged() {
        dispatch("titleChanged");

        if (autoGeneratedImage !== false) {
            console.log("fetching random image");
            fetchRandomImage();
        }
    }

    let autoGeneratedImage: boolean | undefined;

    let showCoverImage = !!article.image;
    let showSummary = !!article.summary;
    let showTags = article.getMatchingTags("t").length > 0;
    let tags: string[] = [];

    $: tags = Array.from(new Set(article.getMatchingTags("t").map(t => t[1])));

    function onSaveCover(article: NDKArticle) {
        autoGeneratedImage = false;
        article = article;
        showCoverImage = !!article.image;
        showTags = article.getMatchingTags("t").length > 0;
        tags = tags;
    }

    function onSaveTags(article: NDKArticle) {
        article = article;
        showCoverImage = !!article.image;
        showTags = article.getMatchingTags("t").length > 0;
        tags = tags;
    }

    let toolbar: NavigationOption[] = [];

    $: {
        toolbar = [];
        if (!article.image || $appMobileView) {
            let name = article.image ? "Change cover image" : "Add cover image";
            toolbar.push({ name, fn: () => openModal(CoverImageModal, { article, onSave: onSaveCover }), class: "!text-xs" });
        }

        if (!showSummary) {
            toolbar.push({ name: "Add summary", fn: () => showSummary = !showSummary });
        }

        if (!showTags) {
            toolbar.push({ name: "Add #hashtags", fn: () => openModal(TagInputModal, { event: article, onSave: onSaveTags }), class: "!text-xs" });
        }
        
        toolbar = toolbar;
    }

</script>

<Content.HeaderShell
    isPreview={false}
    skipImage={!article.image}
>
    <div slot="image" class="w-full h-full relative">
        {#if article.image}
            <div class="text-foreground text-sm font-normal w-full h-full group" transition:slide>
                {#if !$appMobileView}
                    <div class="absolute left-2 top-2 z-50 flex flex-row gap-1 transition-all duration-300 group-hover:opacity-100" class:opacity-50={!!article.image}>
                        <Button forceNonMobile variant="default" size="sm" on:click={() => openModal(CoverImageModal, { article, onSave: onSaveCover })}>
                            {article.image ? "Change" : "Add"} cover image
                        </Button>

                        {#if autoGeneratedImage !== false}
                            <Button forceNonMobile variant="secondary" size="sm" on:click={fetchRandomImage}>
                                <Shuffle class="w-4 h-4 inline" />
                            </Button>
                        {/if}

                    </div>
                {/if}
                
                {#if article.image}
                    <img src={article.image} alt="" class="w-full h-full object-cover" />
                {:else}
                    <div class="text-foreground text-sm font-normal w-full bg-foreground/5 h-full"></div>
                {/if}
            </div>
        {/if}
    </div>

    <div slot="title" class="sticky top-20 max-sm:p-4 max-sm:pb-0">
        <Input
            bind:value={article.title}
            class="!bg-transparent !text-3xl focus-visible:!ring-none focus-visible:!ring-offset-0 focus-visible:!border-none focus-visible:!outline-none !border-none focus:!border-none !p-0 rounded-lg focus:!ring-0 !text-foreground font-['InterDisplay'] placeholder:text-foreground/50 placeholder:font-normal"
            placeholder="Add a title"
            on:keydown={onTitleKeyDown}
            on:change={titleChanged}
        />
    </div>

    <div slot="summary" class="max-sm:px-4" class:hidden={!showSummary}>
        {#if showSummary}
            <ContentEditor
                bind:content={article.summary}
                on:change={() => article = article}
                allowMarkdown={false}
                toolbar={false}
                class="!bg-transparent text-lg border-none !p-0 rounded-lg focus:ring-0 font-['InterDisplay'] text-inherit placeholder:text-muted-foreground/5 !text-muted-foreground 0 placeholder:font-normal"
                placeholder="Summary"
                autofocus={true}
            />
        {/if}
    </div>

    <div slot="toolbar" class="max-sm:p-4">
        {#if !showSummary || !showTags || (!article.image || $appMobileView)}
            <HorizontalOptionsList options={toolbar} class="py-3" />
        {/if}
        {#if showTags}
            <div class="flex flex-row items-center gap-2">
                <Tags {tags} clickable={false} />
                <Button forceNonMobile variant="link" on:click={() => openModal(TagInputModal, { event: article, onSave: onSaveTags })} class="text-sm whitespace-nowrap">Edit #hashtags</Button>
            </div>
        {/if}

        
    </div>
</Content.HeaderShell>

<ArticleRenderShell
    isFullVersion={true}
    isPreview={false}
    skipImage={!article.image}
    class="max-sm:max-h-[50vh]"
>
    

    

    <div slot="content" class="w-full">
        <ContentEditor
            bind:content={article.content}
            on:contentChanged
            on:submit
            on:focus
            on:blur
            class="font-serif text-2xl min-h-[50vh]"
        />
    </div>
</ArticleRenderShell>
