<script lang="ts">
    import Input from '$components/ui/input/input.svelte';
	import { NDKArticle } from "@nostr-dev-kit/ndk";
    import { createEventDispatcher } from "svelte";
	import ArticleRenderShell from "$components/Event/Article/ArticleRenderShell.svelte";
	import { openModal } from "$utils/modal";
	import CoverImageModal from "$modals/CoverImageModal.svelte";
	import TagInputModal from "$modals/TagInputModal.svelte";
	import Tags from "$components/Events/Tags.svelte";
	import { Info, Shuffle, X } from "phosphor-svelte";
	import { Button } from '$components/ui/button';
	import { appMobileView } from '$stores/app';
	import { slide } from 'svelte/transition';
    import * as Content from "$components/Content";
	import HorizontalOptionsList from '$components/HorizontalOptionsList.svelte';
	import ContentEditor from '$components/Forms/ContentEditor.svelte';
    import * as Studio from '$components/Studio';
	import { Writable } from 'svelte/store';
	import { randomImage } from '$utils/image';
	import { NavigationOption } from '../../../../app';
    import * as Tooltip from "$lib/components/ui/tooltip";

    export let state: Writable<Studio.State<Studio.Type.Article>>;
    export let article: NDKArticle = $state.article;

    $: {
        $state.article = article;
        console.log('updating article', article.content);
    }

    const dispatch = createEventDispatcher();

    let contentAreaElement: HTMLElement;

    function onTitleKeyDown(e: KeyboardEvent) {
        if (e.key === "Enter") {
            e.preventDefault();
            // move focus to content
            if (contentAreaElement) contentAreaElement.focus();
        }
    }

    function fetchRandomImage() {
        const url = randomImage(article.title || "Nature", 800, 350)
        article.image = url;
        autoGeneratedImage = true;
        showCoverImage = !!article.image;
    }

    function titleChanged() {
        dispatch("titleChanged");

        if (autoGeneratedImage !== false && !article.image) {
            console.log("fetching random image");
            fetchRandomImage();
        }
    }

    let autoGeneratedImage: boolean | undefined;

    let showCoverImage = !!article.image;
    let showSummary = !!article.summary;
    let showTags = article.getMatchingTags("t").length > 0;
    let tags: string[] = [];

    $: tags = Array.from(new Set(article.getMatchingTags("t").map(t => t[1])));

    function onSaveCover(article: NDKArticle) {
        autoGeneratedImage = false;
        article = article;
        showCoverImage = !!article.image;
        showTags = article.getMatchingTags("t").length > 0;
        tags = tags;
    }

    function onSaveTags(article: NDKArticle) {
        article = article;
        showCoverImage = !!article.image;
        showTags = article.getMatchingTags("t").length > 0;
        tags = tags;
    }

    let toolbar: NavigationOption[] = [];

    $: {
        toolbar = [];
        if (!article.image || $appMobileView) {
            let name = article.image ? "Change cover image" : "Cover image";
            toolbar.push({ name, fn: () => openModal(CoverImageModal, { article, onSave: onSaveCover }), buttonProps: { variant: 'secondary', size: 'xs' } });
        }

        if (!showSummary) {
            toolbar.push({ name: "Add subtitle", fn: () => showSummary = !showSummary, buttonProps: { variant: 'secondary', size: 'xs' } });
        }

        if (!showTags) {
            toolbar.push({ name: "#hashtags", fn: () => openModal(TagInputModal, { event: article, onSave: onSaveTags }), buttonProps: { variant: 'secondary', size: 'xs' } });
        }
        
        toolbar = toolbar;
    }

</script>

<Content.HeaderShell
    isPreview={false}
    skipImage={!article.image}
    ignoreHeader
>
    <div slot="image" class="w-full h-full relative">
        {#if article.image}
            <div class="text-foreground text-sm font-normal w-full h-full group" transition:slide>
                {#if !$appMobileView}
                    <div class="absolute left-2 top-2 z-1 flex flex-row gap-1 transition-all duration-300 group-hover:opacity-100" class:opacity-50={!!article.image}>
                        <Button variant="default" size="sm" on:click={() => openModal(CoverImageModal, { article, onSave: onSaveCover })}>
                            {article.image ? "Change" : "Add"} cover image
                        </Button>

                        {#if autoGeneratedImage !== false}
                            <Button variant="secondary" size="sm" on:click={fetchRandomImage}>
                                <Shuffle class="w-4 h-4 inline" />
                            </Button>
                        {/if}

                    </div>
                {/if}
                
                {#if article.image}
                    <img src={article.image} alt="" class="w-full h-full object-cover" />
                {:else}
                    <div class="text-foreground text-sm font-normal w-full bg-foreground/5 h-full"></div>
                {/if}
            </div>
        {/if}
    </div>

    <div slot="title" class="sticky top-20 max-sm:p-4 max-sm:pb-0" class:mt-6={!article.image}>
        <Input
            bind:value={article.title}
            class="!bg-transparent !text-3xl placeholder:!font-bold focus-visible:!ring-none focus-visible:!ring-offset-0 focus-visible:!border-none focus-visible:!outline-none !border-none focus:!border-none !p-0 rounded-lg focus:!ring-0 !text-foreground font-['InterDisplay'] placeholder:text-foreground/50"
            placeholder="Title"
            on:keydown={onTitleKeyDown}
            on:change={titleChanged}
        />
    </div>

    <div slot="summary" class="max-sm:px-4 relative" class:hidden={!showSummary}>
        {#if showSummary}
            <div class="flex flex-row justify-between items-center">

                <Tooltip.Root>
                    <Tooltip.Trigger>
                        <Info class="w-4 h-4 mr-2" />
                    </Tooltip.Trigger>
                    <Tooltip.Content>
                        Spark your readers' interest; this will be displayed in your article preview.
                    </Tooltip.Content>
                </Tooltip.Root>
                
                <Input
                    bind:value={article.summary}
                    placeholder="Subtitle"
                    on:blur={() => showSummary = !!article.summary && article.summary?.trim().length > 0}
                    class="
                        !bg-transparent font-medium !text-lg text-muted-foreground placeholder:!font-medium focus-visible:!ring-none focus-visible:!ring-offset-0 focus-visible:!border-none focus-visible:!outline-none !border-none focus:!border-none !p-0 rounded-lg focus:!ring-0 font-['InterDisplay'] placeholder:text-muted-foreground/50
                        grow
                    "
                />

                {#if !article.summary || article.summary?.trim().length < 5}
                    <Button size="xs" variant="link" on:click={() => { article.summary = undefined; showSummary = false }} class="text-muted-foreground">
                        Dismiss
                    </Button>
                {/if}
            </div>
        {/if}
    </div>

    <div slot="toolbar" class="max-sm:px-4">
        {#if !showSummary || !showTags || (!article.image || $appMobileView)}
            <HorizontalOptionsList options={toolbar} class="py-3 my-1" />
        {/if}
        {#if showTags}
            <div class="flex flex-row items-center gap-2">
                <Tags {tags} clickable={false} />
                <Button variant="link" on:click={() => openModal(TagInputModal, { event: article, onSave: onSaveTags })} class="text-sm whitespace-nowrap">Edit #hashtags</Button>
            </div>
        {/if}

        
    </div>
</Content.HeaderShell>

<ArticleRenderShell
    isFullVersion={true}
    isPreview={false}
    skipImage={!article.image}
    class="max-sm:max-h-[50vh]"
>
    <div slot="content" class="w-full">
        <ContentEditor
            bind:content={article.content}
            on:contentChanged
            on:submit
            on:focus
            on:blur
            class="article font-serif text-lg min-h-[50vh]"
        />
    </div>
</ArticleRenderShell>
