require_relative '../../../../node_modules/.pnpm/@capacitor+ios@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.pnpm/@capacitor+ios@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.pnpm/@capacitor+ios@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/ios'
  pod 'CapacitorCommunitySqlite', :path => '../../../../node_modules/.pnpm/@capacitor-community+sqlite@6.0.1_@capacitor+core@6.0.0/node_modules/@capacitor-community/sqlite'
  pod 'CapacitorCommunityTextToSpeech', :path => '../../../../node_modules/.pnpm/@capacitor-community+text-to-speech@4.0.1_@capacitor+core@6.0.0/node_modules/@capacitor-community/text-to-speech'
  pod 'CapacitorFirebaseMessaging', :path => '../../../../node_modules/.pnpm/@capacitor-firebase+messaging@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor-firebase/messaging'
  pod 'CapacitorActionSheet', :path => '../../../../node_modules/.pnpm/@capacitor+action-sheet@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../../../node_modules/.pnpm/@capacitor+app@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/app'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/.pnpm/@capacitor+keyboard@6.0.1_@capacitor+core@6.0.0/node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.pnpm/@capacitor+preferences@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/.pnpm/@capacitor+push-notifications@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/.pnpm/@capacitor+share@6.0.0_@capacitor+core@6.0.0/node_modules/@capacitor/share'
  pod 'CapawesomeCapacitorBadge', :path => '../../../../node_modules/.pnpm/@capawesome+capacitor-badge@6.0.0_@capacitor+core@6.0.0/node_modules/@capawesome/capacitor-badge'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
