packages:
  - 'konsta/package'
  - 'ndk/ndk'
  - 'ndk/ndk-cache-redis'
  - 'ndk/ndk-cache-dexie'
  - 'ndk/ndk-cache-nostr'
  - 'ndk/ndk-svelte'
  - 'ndk/ndk-wallet'
  - 'ndk/ndk-svelte-components'
  - 'ndk/packages/*'
