name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  XCODE_VERSION: '15.4'

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    
    - name: Install dependencies
      run: |
        brew install xcodegen
        brew install xcbeautify
    
    - name: Generate Xcode project
      run: ./refresh-project.sh
    
    - name: Build for testing
      run: |
        xcodebuild build-for-testing \
          -project Highlighter.xcodeproj \
          -scheme Highlighter \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
          | xcbeautify
    
    - name: Run tests
      run: |
        xcodebuild test-without-building \
          -project Highlighter.xcodeproj \
          -scheme Highlighter \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro" \
          | xcbeautify || true
EOF < /dev/null